### ISSUE TITLE
提议：增加Server酱消息推送渠道

### ISSUE THREAD

**Issue by WyInnovate** [Shadownc/actions-checkin#1]
佬，参考链接如下
[Server酱](https://sct.ftqq.com/)
[Server酱3](https://sc3.ft07.com/)
[SDK](https://github.com/easychen/serverchan-sdk)

**Comment by Shadownc** [comment]
每人每天5条额度似乎不太够用吧

**Comment by WyInnovate** [comment]
> 每人每天5条额度似乎不太够用吧

我的想法是，如果只签到是够的，然后Server酱支持的渠道非常多，而且配置简单，像企业微信的机器人咋搞我都不会，可以做成可配置项，比如填了KEY就走Server酱，不填就走原先的企业微信渠道

**Comment by Shadownc** [comment]
已新增Server酱 、Qmsg酱

**Comment by WyInnovate** [comment]
> Qmsg酱

这个还真没用过，我去试试

**Comment by Shadownc** [comment]
看文档现在只支持qq私聊推送 不支持群组 群组好像要自己搭
